### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by zloirock** [ungap/raw-json#3]
When I wrote a polyfill for this feature, I considered many different options, including something similar to used in your ponyfill. I already don't remember all the pitfalls I encountered and why I chose full parsing for `parse`. However, your code has at least one obvious problem:

```js
parse('{"a":9007199254740993,"b":9007199254740992}', reviver); // => { a: 9007199254740992, b: 9007199254740992 }
parse('{"a":9007199254740992,"b":9007199254740993}', reviver); // => { a: 9007199254740993n, b: 9007199254740993n }
```

**Comment by WebReflection** [comment]
I see, yes I need to change numbers as key into special strings as key so that each number will preserve its identity, thank you

**Comment by WebReflection** [comment]
Aha, I found a (hopefully) smart way to have the `source` for free without a sweat while preserving, or preventing, collisions. It was a lovely call and gotcha to fix but if you have anything else I didn't think about please do let me know and I'll fix all the things.

The only "*caveat*" I see with this approach is malformed JSON that would throw anyway on `parse` or the possibility that a JSON contains 2**52-1 strings (as values, keys are not pushed) but I think at that point anyone using this module would have a "*slightly bigger problem*" and I don't need to cover terabytes of JSON parsing in my projects that need this feature. Beside that, I think this should work fairly well, fast, and compact 👋
