### ISSUE TITLE
scientific notation with positive exponent e.g. 1e+21

### ISSUE THREAD

**Issue by lameuler** [ungap/raw-json#7]
From what I can see the current regex `[0-9eE.-]+` does not account for numbers in scientific notation with a + at the front of the exponent.

So for example 1e+21 gets replaced to `"1e"+"21"` instead of `"1e+21"` which causes syntax errors when parsing. I think just adding + to the regex character class should fix this?

**Comment by WebReflection** [comment]
Fixed, thanks!
